Repository lirantal/npq, pull requests merged in 2020-10, with the labels that each got.

#150 feat(install scripts): add automatic shell alias installation
  __tests__/scripts.test.js
  package.json
  scripts/postinstall.js
  scripts/preuninstall.js
  scripts/scriptHelpers.js
Labels: enhancement, hacktoberfest

#155 test(install scripts): make install script tests cross-platform
  __tests__/scripts.test.js
Labels: hacktoberfest, hacktoberfest-accepted

#156 fix(install scripts): don't run install script in yarn
  README.md
  __tests__/scripts.test.js
  scripts/postinstall.js
  scripts/scriptHelpers.js
Labels: bug

#158 fix: npq doesn't support the npm alias convention #152
  lib/cliCommons.js
  package.json
  yarn.lock
Labels: enhancement

#159 fix: npq doesn't support the npm alias convention #152 n packages cover
  lib/cliCommons.js
Labels: bug, hacktoberfest-accepted
