Repository lirantal/npq, pull requests merged in 2025-08, with the labels that each got.

#341 Fix/address deprecation warning dep0190
  __tests__/env-var-integration.test.js
  __tests__/packageManager.test.js
  lib/packageManager.js
Labels: bug, Review effort 2/5, Possible security concern

#345 chore: improve CI
  .github/workflows/main.yml
Labels: Review effort 2/5

#350 chore(tests): skip shell tests on Windows
  __tests__/scripts.test.js
Labels: enhancement, Review effort 2/5

#354 chore: fix some CodeQL issues
  __tests__/marshalls.snyk.test.js
  lib/helpers/packageRepoUtils.js
  lib/helpers/reportResults.js
  lib/marshalls/author.marshall.js
  lib/marshalls/license.marshall.js
  lib/marshalls/provenance.marshall.js
  lib/marshalls/signatures.marshall.js
  lib/marshalls/snyk.marshall.js
  lib/marshallsDecomissioned/readme.marshall.js
  scripts/build.js
Labels: enhancement, Review effort 2/5

#353 chore: use the direct images from the repo and minor markdown tweaks
  .github/nodejs-security-screenshot.png
  README.md
Labels: Review effort 2/5

#357 Fix: deps upgrade
  .husky/commit-msg
  .husky/post-merge
  .husky/pre-commit
  .husky/pre-push
  eslint.config.js
  package-lock.json
  package.json
Labels: enhancement, Review effort 3/5

#360 fix: refactor base marshall to support package alias version parsing
  __tests__/marshalls.newBin.test.js
  __tests__/marshalls.version-maturity.test.js
  eslint.config.js
  lib/marshalls/age.marshall.js
  lib/marshalls/baseMarshall.js
  lib/marshalls/deprecation.marshall.js
  lib/marshalls/newbin.marshall.js
  lib/marshalls/provenance.marshall.js
  lib/marshalls/scripts.marshall.js
  lib/marshalls/version-maturity.marshall.js
Labels: bug, Review effort 3/5, Possible security concern

#362 Fix/date diff incorrect ms usage
  .gitignore
  __tests__/marshalls.age.test.js
  docs/age.marshall.md
  lib/marshalls/age.marshall.js
Labels: bug, Review effort 2/5

#371 feat: unify marshall result formatting (#368)
  __tests__/marshalls.age.test.js
  __tests__/marshalls.version-maturity.test.js
  lib/marshalls/age.marshall.js
  lib/marshalls/downloads.marshall.js
  lib/marshalls/version-maturity.marshall.js
Labels: enhancement, Review effort 2/5

#370 revert: remove unused test file
  test-ctrl-c-fix.js
Labels: bug, Review effort 1/5
